language: ruby # don't install any environment
#cache: bundler

sudo: false
rvm:
  - 2.6
before_install:
  - gem install bundler
  - bundle update
script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "648e013eb731"
  - COMMIT_AUTHOR_EMAIL: "contact@thirtybees.com"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true

branches:
  only:
  - master
